### ISSUE TITLE
docs(theming): add a section on how to add a new color 

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#159]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**URL:**
https://beta.ionicframework.com/docs/theming/advanced

When I added this documentation I went in depth on how to change the existing colors, but I forgot to document how to add a new one. Basically document this: https://github.com/ionic-team/ionic-conference-app/blob/master/src/theme/variables.scss#L88-L139

In case the link dies:

```
// Additional Ionic Colors
// --------------------------------------------------
// In order to add colors to be used with Ionic components,
// the color should be added as a class with the convention `.ion-color-{COLOR}`
// where `{COLOR}` is the color to be used on the Ionic component
// and each variant is defined for the color. For more information, please see
// https://beta.ionicframework.com/docs/theming/advanced

.ion-color-favorite {
  --ion-color-base: #69bb7b;
  --ion-color-base-rgb: 105,187,123;
  --ion-color-contrast: #ffffff;
  --ion-color-contrast-rgb: 255,255,255;
  --ion-color-shade: #5ca56c;
  --ion-color-tint: #78c288;
}
```

Also document how they can use it in their app, basically they need to define the variable with whatever name they'd like, but I think we should encourage the `--ion` naming convention:

```css
:root {
  --ion-color-favorite: #69bb7b;
  --my-color: #444;
}
```

```css
body {
  background: var(--ion-color-favorite);
  color: var(--my-color);
}
```
