### ISSUE TITLE
content: CSS Custom Properties for ion-input

### ISSUE THREAD

**Issue by hannesthor** [ionic-team/ionic-docs#2983]
### Describe the Bug

The example in the documentation indicates that you can change the color on the helper and counter. However, try to change the color to, e.g. red, it does not work. 

https://ionicframework.com/docs/api/input#css-custom-properties

### Expected Behavior

Expect it to work as stated in the documentation

### Steps to Reproduce

Follow the link to Stackblitz in the documentation, try to change the color in the following CSS

```css
ion-input.custom .helper-text,
ion-input.custom .counter {
  color: var(--ion-color-step-700, #373737);
}
```

### Operating System

Windows

### Browser

Chrome

### Version

113
