### ISSUE TITLE
Header cropped on mobile

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-docs#314]
Can't click the other links in the header.

![image](https://user-images.githubusercontent.com/236501/51621046-45e77f00-1ef9-11e9-983e-d459b67a0d5b.png)

Maybe a quick fix would be:

```css
docs-header header {
  overflow-y: scroll;
}
```
