### ISSUE TITLE
feat: Modal with dynamic height. Docs for class ion-page.

### ISSUE THREAD

**Issue by fudom** [ionic-team/ionic-docs#3424]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Describe the `ion-page` class which is automatically added on runtime when using modal controller to view a component. Consider adding an option to prevent adding this class.

### Describe the Use Case

Showing a modal with dynamic height but with scollable content makes is very challenging in Ionic. In the [docs here](https://ionicframework.com/docs/ja/v6/api/modal) I see the usage of `ion-page`. But no description why and what this is. 

Maybe it would be also great if there is an example of modal with dynamic height (created via controller). And/or add an option to the modal to simply set a modal with dynamic height. In my case, I want a sticky header and scrollable the content with max-height 100%. The ion-content is not suitable for that, because it's always height 0 in a dynamic context. So I replaced it by a div.

My current solution:

[Playground](https://stackblitz.com/edit/ionic6-angular13-hcesm1?file=src%2Fstyles.css)

![demo](https://github.com/ionic-team/ionic-framework/assets/143608856/5dcb85da-de2d-4444-9abc-a75bfe56e4de)

Change the window width and height. Here is the [demo](https://ionic6-angular13-hcesm1.stackblitz.io) without editor. You can use the DevTool device view to allow smaller view sizes.

```scss
ion-modal {
  --width: 100%;
  --height: 100%;
  --max-width: 600px;
  --max-height: 600px;
  --border-radius: 5px;
  --box-shadow: 0 28px 48px rgba(0, 0, 0, 0.4);
  padding: 10px;
}

ion-modal.dynamic-height {
  --width: 100%;
  --height: unset;
  --max-height: 100%;

  &::part(content) {
    overflow: auto;
  }

  .ion-page {
    overflow: unset;

    ion-header {
      position: sticky;
      top: 0;
    }
  }
}
```

What does this code?

- Ensure the modal is always displayed as modal. Never view it in fullscreen. Keep padding, rounded corners and shadow. Also a max-width and max-height. The appearance should be a modal overview. Never mock a page.

- Dynamic height by unchain the height. But max-height to screen edge for later scrolling. In this solution we use the content for scroll (overflow: auto). And the overflow of ion-page (which is added to the component) needs to be unset. This allows us to use sticky header.

So it works. I found a solution. But could we please support this in a easier way? There are other solutions too. Maybe with ion-content? No need for sticky header then. Maybe you got the point. Don't hesitate to ask me for more information. I just don't want to hack or write a book to have such modals. That do you think? Can Ionic support it?

The problem with ion-page added to the modal component, is that this makes the page display flex with space between. Without ion-content, you have a gap here and content is not scollable anymore.
